In [13]:
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import missingno as msno
from sklearn.linear_model import Ridge
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('max_colwidth',100)

data = pd.read_csv('delete3_2.csv', sep=',')

Y1 = data['y1']
Y2 = data['y2']
X = data[['x320', 'x182', 'x61', 'x54', 'x239', 'x244']]

clf1 = Ridge()
clf1.fit(X, Y1)
clf2 = Ridge()
clf2.fit(X, Y2)

x = np.array([0.6895, 270.3794, 369.3962, 61.52, 8.8463, -0.4479]).reshape(1, -1)

result = []
y_pred = clf1.predict(x)
result.append(y_pred)
for i in range(150):
    if x[0][0]<300:
        x[0][0] = x[0][0]+2
    result.append(clf1.predict(x))

result = pd.DataFrame(result)
result.to_csv('硫含量调完x320.csv')

In [14]:
x

array([[300.6895, 270.3794, 369.3962,  61.52  ,   8.8463,  -0.4479]])

In [15]:
result_2 = []
y_pred = clf1.predict(x)
result_2.append(y_pred)
for i in range(27):
    if x[0][1]>1.5:
        x[0][1] = x[0][1]-10
    result_2.append(clf1.predict(x))

result_2 = pd.DataFrame(result_2)
result_2.to_csv('硫含量调完x320x182.csv')

In [16]:
x

array([[300.6895,   0.3794, 369.3962,  61.52  ,   8.8463,  -0.4479]])

In [17]:
result_3 = []
y_pred = clf1.predict(x)
result_3.append(y_pred)
for i in range(7):
    if x[0][2]>362:
        x[0][2] = x[0][2]-1
    result_3.append(clf1.predict(x))

result_3 = pd.DataFrame(result_3)
result_3.to_csv('硫含量调完x320x182x61.csv')

In [18]:
x

array([[300.6895,   0.3794, 362.3962,  61.52  ,   8.8463,  -0.4479]])

In [19]:
result_4 = []
y_pred = clf1.predict(x)
result_4.append(y_pred)
for i in range(26):
    if x[0][3]>35:
        x[0][3] = x[0][3]-1
    result_4.append(clf1.predict(x))

result_4 = pd.DataFrame(result_4)
result_4.to_csv('硫含量调完x320x182x61x54.csv')

In [20]:
x

array([[300.6895,   0.3794, 362.3962,  35.52  ,   8.8463,  -0.4479]])

In [21]:
result_5 = []
y_pred = clf1.predict(x)
result_5.append(y_pred)
for i in range(4):
    if x[0][4]<12:
        x[0][4] = x[0][4]+1
    result_5.append(clf1.predict(x))

result_5 = pd.DataFrame(result_5)
result_5.to_csv('硫含量调完x320x182x61x54x239.csv')

In [22]:
x

array([[300.6895,   0.3794, 362.3962,  35.52  ,  12.8463,  -0.4479]])

In [23]:
result_6 = []
y_pred = clf1.predict(x)
result_6.append(y_pred)
for i in range(26):
    if x[0][5]<25:
        x[0][5] = x[0][5]+1
    result_6.append(clf1.predict(x))

result_6 = pd.DataFrame(result_6)
result_6.to_csv('硫含量调完x320x182x61x54x239x244.csv')

In [24]:
x

array([[300.6895,   0.3794, 362.3962,  35.52  ,  12.8463,  25.5521]])