In [68]:
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import missingno as msno
from sklearn.linear_model import Ridge
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('max_colwidth',100)

data = pd.read_csv('delete3_2.csv', sep=',')

Y1 = data['y1']
Y2 = data['y2']
X = data[['x320', 'x182', 'x61', 'x54', 'x239', 'x244']]

clf1 = Ridge()
clf1.fit(X, Y1)
clf2 = Ridge()
clf2.fit(X, Y2)

x = np.array([0.6895, 270.3794, 369.3962, 61.52, 8.8463, -0.4479]).reshape(1, -1)

result = []
y_pred = clf2.predict(x)
result.append(y_pred)
for i in range(150):
    if x[0][0]<300:
        x[0][0] = x[0][0]+2
    result.append(clf2.predict(x))

result = pd.DataFrame(result)

x1 = pd.DataFrame([89.40 for i in range(151)])
result_end = x1 - result

In [69]:
result_end.to_csv('调完x320.csv')

In [70]:
x

array([[300.6895, 270.3794, 369.3962,  61.52  ,   8.8463,  -0.4479]])

In [71]:
result_2 = []
y_pred = clf2.predict(x)
result_2.append(y_pred)
for i in range(27):
    if x[0][1]>1.5:
        x[0][1] = x[0][1]-10
    result_2.append(clf2.predict(x))
result_2 = pd.DataFrame(result_2)
x1 = pd.DataFrame([89.40 for i in range(28)])
result_2_end = x1 - result_2

In [72]:
result_2_end.to_csv('调完x320x182.csv')

In [73]:
x

array([[300.6895,   0.3794, 369.3962,  61.52  ,   8.8463,  -0.4479]])

In [74]:
result_3 = []
result_3.append(clf2.predict(x))
for i in range(7):
    if x[0][2]>362:
        x[0][2] = x[0][2]-1
    result_3.append(clf2.predict(x))

result_3 = pd.DataFrame(result_3)
x1 = pd.DataFrame([89.40 for i in range(8)])
result_3_end = x1 - result_3
result_3_end.to_csv('调完x320x182x61.csv')

In [75]:
x

array([[300.6895,   0.3794, 362.3962,  61.52  ,   8.8463,  -0.4479]])

In [76]:
result_4 = []
y_pred = clf2.predict(x)
result_4.append(y_pred)
for i in range(26):
    if x[0][3]>35:
        x[0][3] = x[0][3]-1
    result_4.append(clf2.predict(x))

result_4 = pd.DataFrame(result_4)
x1 = pd.DataFrame([89.40 for i in range(27)])
result_4_end = x1 - result_4
result_4_end.to_csv('调完x320x182x61x54.csv')

In [77]:
x

array([[300.6895,   0.3794, 362.3962,  35.52  ,   8.8463,  -0.4479]])

In [78]:
result_5 = []
y_pred = clf2.predict(x)
result_5.append(y_pred)
for i in range(4):
    if x[0][4]<12:
        x[0][4] = x[0][4]+1
    result_5.append(clf2.predict(x))
x1 = pd.DataFrame([89.40 for i in range(5)])
result_5 = pd.DataFrame(result_5)
result_5_end = x1 - result_5
result_5_end.to_csv('调完x320x182x61x54x239.csv')

In [79]:
x

array([[300.6895,   0.3794, 362.3962,  35.52  ,  12.8463,  -0.4479]])

In [80]:
result_6 = []
y_pred = clf2.predict(x)
result_6.append(y_pred)
for i in range(26):
    if x[0][5]<25:
        x[0][5] = x[0][5]+1
    result_6.append(clf2.predict(x))
x1 = pd.DataFrame([89.40 for i in range(27)])
result_6 = pd.DataFrame(result_6)
result_6_end = x1 - result_6
result_6_end.to_csv('调完x320x182x61x54x239x244.csv')

In [81]:
qwe = pd.read_csv('调完x320.csv', sep=',')

In [82]:
time = qwe['time']
data_qwe = qwe['data']

time       data
0       0  88.058684
1       1  88.060092
2       2  88.061501
3       3  88.062909
4       4  88.064317
5       5  88.065726
6       6  88.067134
7       7  88.068542
8       8  88.069951
9       9  88.071359
10     10  88.072767
11     11  88.074176
12     12  88.075584
13     13  88.076993
14     14  88.078401
15     15  88.079809
16     16  88.081218
17     17  88.082626
18     18  88.084034
19     19  88.085443
20     20  88.086851
21     21  88.088260
22     22  88.089668
23     23  88.091076
24     24  88.092485
25     25  88.093893
26     26  88.095301
27     27  88.096710
28     28  88.098118
29     29  88.099527
30     30  88.100935
31     31  88.102343
32     32  88.103752
33     33  88.105160
34     34  88.106568
35     35  88.107977
36     36  88.109385
37     37  88.110794
38     38  88.112202
39     39  88.113610
40     40  88.115019
41     41  88.116427
42     42  88.117835
43     43  88.119244
44     44  88.120652
45     45  88.122061
46     46  88.123469
47     47  88.124877
48     48  88.126286
49     49  88.127694
50     50  88.129102
51     51  88.130511
52     52  88.131919
53     53  88.133328
54     54  88.134736
55     55  88.136144
56     56  88.137553
57     57  88.138961
58     58  88.140369
59     59  88.141778
60     60  88.143186
61     61  88.144595
62     62  88.146003
63     63  88.147411
64     64  88.148820
65     65  88.150228
66     66  88.151636
67     67  88.153045
68     68  88.154453
69     69  88.155862
70     70  88.157270
71     71  88.158678
72     72  88.160087
73     73  88.161495
74     74  88.162903
75     75  88.164312
76     76  88.165720
77     77  88.167128
78     78  88.168537
79     79  88.169945
80     80  88.171354
81     81  88.172762
82     82  88.174170
83     83  88.175579
84     84  88.176987
85     85  88.178395
86     86  88.179804
87     87  88.181212
88     88  88.182621
89     89  88.184029
90     90  88.185437
91     91  88.186846
92     92  88.188254
93     93  88.189662
94     94  88.191071
95     95  88.192479
96     96  88.193888
97     97  88.195296
98     98  88.196704
99     99  88.198113
100   100  88.199521
101   101  88.200929
102   102  88.202338
103   103  88.203746
104   104  88.205155
105   105  88.206563
106   106  88.207971
107   107  88.209380
108   108  88.210788
109   109  88.212196
110   110  88.213605
111   111  88.215013
112   112  88.216422
113   113  88.217830
114   114  88.219238
115   115  88.220647
116   116  88.222055
117   117  88.223463
118   118  88.224872
119   119  88.226280
120   120  88.227689
121   121  88.229097
122   122  88.230505
123   123  88.231914
124   124  88.233322
125   125  88.234730
126   126  88.236139
127   127  88.237547
128   128  88.238955
129   129  88.240364
130   130  88.241772
131   131  88.243181
132   132  88.244589
133   133  88.245997
134   134  88.247406
135   135  88.248814
136   136  88.250222
137   137  88.251631
138   138  88.253039
139   139  88.254448
140   140  88.255856
141   141  88.257264
142   142  88.258673
143   143  88.260081
144   144  88.261489
145   145  88.262898
146   146  88.264306
147   147  88.265715
148   148  88.267123
149   149  88.268531
150   150  88.269940